### ISSUE TITLE
Transfer Line Attribute tool results in an error

### ISSUE THREAD

**Issue by jesselangdon** [SouthForkResearch/gnat#10]
Encountered this error when recently testing out the Transfer Line Attribute table.
```
Messages
Executing: TransferLineAttributesTool C:\JL\Testing\GNAT\TransferLineAttributes\input.gdb\seg1000m_entiat C:\JL\Testing\GNAT\TransferLineAttributes\input.gdb\nhd100k_entiat LineOID C:\JL\Testing\GNAT\TransferLineAttributes\output.gdb\seg1000m_to_nhd100k C:\JL\Testing\GNAT\TransferLineAttributes\scratch.gdb
Start Time: Tue Jan 03 12:47:14 2017
Running script TransferLineAttributesTool...
GNAT TLA | Branch: 1

Traceback (most recent call last):
  File "<string>", line 353, in execute
  File "C:\dev\geomorphic-network-and-analysis-toolbox\TransferAttributesToLine.py", line 56, in main
    arcpy.Buffer_analysis(lyrToLineBranch,fcToLineBuffer,"10 Meters","FULL","ROUND","ALL")
  File "c:\program files (x86)\arcgis\desktop10.1\arcpy\arcpy\analysis.py", line 686, in Buffer
    raise e
ExecuteError: ERROR 999999: Error executing function.
An expected Field was not found or could not be retrieved properly.
An expected Field was not found or could not be retrieved properly. [nhd100k_entiat]
An expected Field was not found or could not be retrieved properly.
An expected Field was not found or could not be retrieved properly. [nhd100k_entiat]
An expected Field was not found or could not be retrieved properly.
An expected Field was not found or could not be retrieved properly. [nhd100k_entiat]
The table was not found. [GNAT_TLA_ToLineBuffer_1]
Failed to execute (Buffer).

Failed to execute (TransferLineAttributesTool).
Failed at Tue Jan 03 12:47:17 2017 (Elapsed Time: 3.00 seconds)
```

**Comment by jesselangdon** [comment]
I'll take this on Kelly.

**Comment by jesselangdon** [comment]
Basically I just removed for BranchID option and associated code.  This takes care of the above mentioned error
